server:
  port: 8081

spring:
  application:
    name: config-server

#eureka连接信息
eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka/

#开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
