spring:
  application:
    name: gateway-server
server:
  port: 8080

#eureka连接信息
eureka:
  instance:
    hostname: summer.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS