server:
  port: 8762

spring:
  application:
    name: admin-server
  #eureka权限配置
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      context-path: admin #admin界面与eureka分离

#eureka连接信息
eureka:
  instance:
    hostname: summer.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    com.netflix: warn